[package]
name = "ssrproxy"
version = "0.1.0"
authors = ["Vidy Videni <vidy.videni@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
oauth2 = { version = "3.0", features = ["futures-01"] }
diesel = { version = "1.4.6", features = ["mysql"] }
chrono = "0.4.6"
